site_name: 我的笔记本
site_url: https://griffindorr.github.io/profile/
site_description: 个人技术笔记
site_author: dongjian
copyright: Copyright &copy; 2026 dongjian

repo_name: Griffindorr/profile
repo_url: https://github.com/Griffindorr/profile
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

plugins:
  - search:
      lang: zh
  - glightbox
  - git-revision-date-localized:
      type: date
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

validation:
  nav:
    omitted_files: info
    not_found: warn
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

nav:
  - 首页:
      - index.md
  - 计算机:
      - cs/index.md
      - Rust:
          - 基础语法: cs/rust/basic.md